name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.Ayushhh-15 }} -p ${{ secrets.Hezakmi@12 }}

      - name: Build image
        run: docker build -t Ayushhh-15/lab11-devops .

      - name: Push image
        run: docker push Ayushhh-15/lab11-devops
